### ISSUE TITLE
[Bug]: undefined method `archived' for an instance of App

### ISSUE THREAD

**Issue by vespersio** [tryzealot/zealot#2122]
### 部署方式 | How to Deploy

Kubernates

### 部署版本 | Version

6.1.0

### Git 哈希值 (长度 40)| Git Ref (40 length)

4d33987

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [x] 已阅读 | Yes

### 描述 | Description

After upgrade from nightly-2025-04-10 to 6.1.0

### 问题日志 | Relevant log output

```shell
undefined method `archived' for an instance of App
```

**Comment by icyleaf** [comment]
I never expected anyone would downgrade from nightly to the stable version. In theory, this error shouldn’t occur — it’s a highly unlikely issue. `archived` is a field in the `app` table; please confirm whether it exists.

To understand the cause of this issue, please provide the full logs from the moment the service starts up until the error appears. That would be more helpful.
